<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SekkaShawarmaSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            [
                'key' => 'ultramsg_token',
                'value' => 'b6ght2y2ff7rbha6',
                'type' => 'string',
                'group' => 'whatsapp',
                'display_name' => 'UltraMsg Token',
                'description' => 'Your UltraMsg API token',
                'is_public' => 0,
                'created_at' => '2025-08-23 04:51:51',
                'updated_at' => '2025-08-23 04:51:51',
            ],
            [
                'key' => 'ultramsg_instance_id',
                'value' => 'instance139458',
                'type' => 'string',
                'group' => 'whatsapp',
                'display_name' => 'UltraMsg Instance ID',
                'description' => 'Your UltraMsg instance ID',
                'is_public' => 0,
                'created_at' => '2025-08-23 04:51:51',
                'updated_at' => '2025-08-23 04:51:51',
            ],
            [
                'key' => 'company_phone_2',
                'value' => '',
                'type' => 'string',
                'group' => 'company',
                'display_name' => 'Company Phone 2',
                'description' => 'The second phone number of your company',
                'is_public' => 1,
                'created_at' => '2025-08-23 04:51:51',
                'updated_at' => '2025-08-23 12:02:09',
            ],
            [
                'key' => 'pos_auto_send_whatsapp_invoice',
                'value' => 'false',
                'type' => 'boolean',
                'group' => 'pos',
                'display_name' => 'Auto Send WhatsApp Invoice',
                'description' => 'Automatically send PDF invoice via WhatsApp when order is completed',
                'is_public' => 0,
                'created_at' => '2025-08-23 04:51:52',
                'updated_at' => '2025-08-23 04:51:52',
            ],
            [
                'key' => 'pos_auto_send_whatsapp_text',
                'value' => 'false',
                'type' => 'boolean',
                'group' => 'pos',
                'display_name' => 'Auto Send WhatsApp Text',
                'description' => 'Automatically send WhatsApp text message when order is completed',
                'is_public' => 0,
                'created_at' => '2025-08-23 04:51:52',
                'updated_at' => '2025-08-23 04:51:52',
            ],
            [
                'key' => 'pos_auto_send_receive_order_message',
                'value' => 'false',
                'type' => 'boolean',
                'group' => 'pos',
                'display_name' => 'Auto Send Receive Order Message',
                'description' => 'Automatically send WhatsApp message when order is received',
                'is_public' => 0,
                'created_at' => '2025-08-23 04:51:52',
                'updated_at' => '2025-08-23 04:51:52',
            ],
            [
                'key' => 'pos_show_item_notes_in_pdf',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'pos',
                'display_name' => 'Show Item Notes in PDF',
                'description' => 'Show individual item notes in POS invoice PDF',
                'is_public' => 0,
                'created_at' => '2025-08-23 04:51:52',
                'updated_at' => '2025-08-23 04:51:52',
            ],
            [
                'key' => 'company_name',
                'value' => 'SEKKA SHAWARMA',
                'type' => 'string',
                'group' => 'company',
                'display_name' => 'Company Name',
                'description' => 'The name of your company',
                'is_public' => 1,
                'created_at' => null,
                'updated_at' => '2025-08-23 12:02:09',
            ],
            [
                'key' => 'company_address',
                'value' => 'ولاية المصنعة الشعيبة',
                'type' => 'string',
                'group' => 'company',
                'display_name' => 'Company Address',
                'description' => 'The address of your company',
                'is_public' => 1,
                'created_at' => null,
                'updated_at' => '2025-08-23 12:02:09',
            ],
            [
                'key' => 'company_phone',
                'value' => '96496452',
                'type' => 'string',
                'group' => 'company',
                'display_name' => 'Company Phone',
                'description' => 'The phone number of your company',
                'is_public' => 1,
                'created_at' => null,
                'updated_at' => '2025-08-23 12:02:09',
            ],
            [
                'key' => 'company_email',
                'value' => 'contact@example.com',
                'type' => 'string',
                'group' => 'company',
                'display_name' => 'Company Email',
                'description' => 'The email address of your company',
                'is_public' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'company_logo_url',
                'value' => 'http://127.0.0.1/laundry/jawda-laundry-backend/public/storage/logos/41q0UCSg7bLDaMUQX8aTy40VRfLtksQw16IPbRFO.png',
                'type' => 'string',
                'group' => 'company',
                'display_name' => 'Company Logo URL',
                'description' => 'URL to your company logo',
                'is_public' => 1,
                'created_at' => null,
                'updated_at' => '2025-08-23 12:02:40',
            ],
            [
                'key' => 'app_name',
                'value' => 'Jawda Restaurant',
                'type' => 'string',
                'group' => 'app',
                'display_name' => 'App Name',
                'description' => 'The name displayed in the app bar and login page',
                'is_public' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'app_description',
                'value' => 'RESTAURANT MANAGEMENT SYSTEM',
                'type' => 'string',
                'group' => 'app',
                'display_name' => 'App Description',
                'description' => 'The description displayed on the login page',
                'is_public' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'currency_symbol',
                'value' => 'OMR',
                'type' => 'string',
                'group' => 'general',
                'display_name' => 'Currency Symbol',
                'description' => 'The currency symbol used throughout the application',
                'is_public' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'date_format',
                'value' => 'YYYY-MM-DD',
                'type' => 'string',
                'group' => 'general',
                'display_name' => 'Date Format',
                'description' => 'The date format used throughout the application',
                'is_public' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'country_code',
                'value' => '968',
                'type' => 'string',
                'group' => 'general',
                'display_name' => 'Default Country Code',
                'description' => 'The default country code used throughout the application',
                'is_public' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'global_low_stock_threshold',
                'value' => '10',
                'type' => 'integer',
                'group' => 'general',
                'display_name' => 'Low Stock Threshold',
                'description' => 'The threshold for low stock warnings',
                'is_public' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'invoice_prefix',
                'value' => 'INV-',
                'type' => 'string',
                'group' => 'invoice',
                'display_name' => 'Invoice Prefix',
                'description' => 'Prefix for invoice numbers',
                'is_public' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'purchase_order_prefix',
                'value' => 'PO-',
                'type' => 'string',
                'group' => 'invoice',
                'display_name' => 'Purchase Order Prefix',
                'description' => 'Prefix for purchase order numbers',
                'is_public' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'invoice_thermal_footer',
                'value' => 'شكراً لزيارتكم!زورونا مرة أخرى!',
                'type' => 'string',
                'group' => 'invoice',
                'display_name' => 'Thermal Invoice Footer',
                'description' => 'Footer text for thermal invoices',
                'is_public' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'payment_methods_ar',
                'value' => '{"cash":"\u0646\u0642\u062f\u064a","visa":"\u0641\u064a\u0632\u0627","mastercard":"\u0645\u0627\u0633\u062a\u0631\u0643\u0627\u0631\u062f","bank_transfer":"\u062a\u062d\u0648\u064a\u0644 \u0628\u0646\u0643\u064a","mada":"\u0645\u062f\u0649","store_credit":"\u0631\u0635\u064a\u062f \u0645\u062a\u062c\u0631","other":"\u0623\u062e\u0631\u0649"}',
                'type' => 'json',
                'group' => 'payment',
                'display_name' => 'Payment Methods (Arabic)',
                'description' => 'Arabic translations for payment methods',
                'is_public' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'whatsapp_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'whatsapp',
                'display_name' => 'Enable WhatsApp',
                'description' => 'Enable WhatsApp notifications using UltraMsg API',
                'is_public' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'whatsapp_notification_number',
                'value' => '78622990',
                'type' => 'string',
                'group' => 'whatsapp',
                'display_name' => 'WhatsApp Notification Number',
                'description' => 'The phone number for WhatsApp notifications',
                'is_public' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'whatsapp_country_code',
                'value' => '968',
                'type' => 'string',
                'group' => 'whatsapp',
                'display_name' => 'WhatsApp Country Code',
                'description' => 'The country code for WhatsApp',
                'is_public' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'pos_auto_show_pdf',
                'value' => 'false',
                'type' => 'boolean',
                'group' => 'pos',
                'display_name' => 'Auto Show PDF',
                'description' => 'Automatically show PDF after order completion',
                'is_public' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'pos_show_products_as_list',
                'value' => 'false',
                'type' => 'boolean',
                'group' => 'pos',
                'display_name' => 'Show Products as List',
                'description' => 'Show products in list format instead of grid',
                'is_public' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'theme_primary_color',
                'value' => 'sky',
                'type' => 'string',
                'group' => 'theme',
                'display_name' => 'Primary Color',
                'description' => 'The primary color theme',
                'is_public' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'key' => 'theme_secondary_color',
                'value' => 'blue',
                'type' => 'string',
                'group' => 'theme',
                'display_name' => 'Secondary Color',
                'description' => 'The secondary color theme',
                'is_public' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
        ];

        foreach ($settings as $setting) {
            DB::table('settings')->updateOrInsert(
                ['key' => $setting['key']],
                $setting
            );
        }

        $this->command->info('Sekka Shawarma settings seeded successfully!');
    }
}
